### ISSUE TITLE
npm i fails for me on "feature/coding-standards" branch

### ISSUE THREAD

**Issue by salcode** [WebDevStudios/wd_s#631]
While on the `feature/coding-standards` branch (at commit 63a427e) using the recommended versions of `npm` and `node`, the command `npm i` fails for me.

Related #630 

```
$ nvm use
Found '/Users/sal/code/wpgeneric/app/public/wp-content/themes/wd_s/.nvmrc' with version <lts/*>
Now using node v12.18.3 (npm v6.14.6)
```

```
$ npm i
npm WARN read-shrinkwrap This version of npm is compatible with lockfileVersion@1, but package-lock.json was generated for lockfileVersion@2. I'll try to do my best with it!

> husky@4.3.8 preuninstall /Users/sal/code/wpgeneric/app/public/wp-content/themes/wd_s/node_modules/husky
> node husky uninstall

husky > Uninstalling git hooks
husky > Done

> core-js@3.10.0 postinstall /Users/sal/code/wpgeneric/app/public/wp-content/themes/wd_s/node_modules/core-js
> node -e "try{require('./postinstall')}catch(e){}"

Thank you for using core-js ( https://github.com/zloirock/core-js ) for polyfilling JavaScript standard library!

The project needs your help! Please consider supporting of core-js on Open Collective or Patreon:
> https://opencollective.com/core-js
> https://www.patreon.com/zloirock

Also, the author of core-js ( https://github.com/zloirock ) is looking for a good job -)


> core-js-pure@3.10.0 postinstall /Users/sal/code/wpgeneric/app/public/wp-content/themes/wd_s/node_modules/core-js-pure
> node -e "try{require('./postinstall')}catch(e){}"


> wd_s@2.0.1 postinstall /Users/sal/code/wpgeneric/app/public/wp-content/themes/wd_s
> composer install --quiet && npm run build


> wd_s@2.0.1 build /Users/sal/code/wpgeneric/app/public/wp-content/themes/wd_s
> cross-env NODE_ENV=production run-s build:*

events.js:292
      throw er; // Unhandled 'error' event
      ^

Error: spawn run-s ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:267:19)
    at onErrorNT (internal/child_process.js:469:16)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
Emitted 'error' event on ChildProcess instance at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:273:12)
    at onErrorNT (internal/child_process.js:469:16)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  errno: 'ENOENT',
  code: 'ENOENT',
  syscall: 'spawn run-s',
  path: 'run-s',
  spawnargs: [ 'build:*' ]
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! wd_s@2.0.1 build: `cross-env NODE_ENV=production run-s build:*`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the wd_s@2.0.1 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/sal/.npm/_logs/2021-04-14T19_36_00_665Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! wd_s@2.0.1 postinstall: `composer install --quiet && npm run build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the wd_s@2.0.1 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/sal/.npm/_logs/2021-04-14T19_36_00_993Z-debug.log
themes/wd_s (feature/coding-standards)$ clear

themes/wd_s (feature/coding-standards)$ nvm use
Found '/Users/sal/code/wpgeneric/app/public/wp-content/themes/wd_s/.nvmrc' with version <lts/*>
Now using node v12.18.3 (npm v6.14.6)
themes/wd_s (feature/coding-standards)$ npm i
npm WARN read-shrinkwrap This version of npm is compatible with lockfileVersion@1, but package-lock.json was generated for lockfileVersion@2. I'll try to do my best with it!

> wd_s@2.0.1 postinstall /Users/sal/code/wpgeneric/app/public/wp-content/themes/wd_s
> composer install --quiet && npm run build


> wd_s@2.0.1 build /Users/sal/code/wpgeneric/app/public/wp-content/themes/wd_s
> cross-env NODE_ENV=production run-s build:*

events.js:292
      throw er; // Unhandled 'error' event
      ^

Error: spawn run-s ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:267:19)
    at onErrorNT (internal/child_process.js:469:16)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
Emitted 'error' event on ChildProcess instance at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:273:12)
    at onErrorNT (internal/child_process.js:469:16)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  errno: 'ENOENT',
  code: 'ENOENT',
  syscall: 'spawn run-s',
  path: 'run-s',
  spawnargs: [ 'build:*' ]
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! wd_s@2.0.1 build: `cross-env NODE_ENV=production run-s build:*`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the wd_s@2.0.1 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/sal/.npm/_logs/2021-04-14T19_39_49_038Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! wd_s@2.0.1 postinstall: `composer install --quiet && npm run build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the wd_s@2.0.1 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/sal/.npm/_logs/2021-04-14T19_39_49_111Z-debug.log
```

[Gist of /Users/sal/.npm/_logs/2021-04-14T19_39_49_111Z-debug.log](https://gist.github.com/salcode/4014f71100d72448a884e5c51658ab05)

**Comment by gregrickaby** [comment]
@salcode Interesting. When I type `nvm use` I get:

```bash
➜  wd_s git:(feature/coding-standards) ✗ nvm use    
Found '/Users/gregoryrickaby/Local/wdunderscores/app/public/wp-content/themes/wd_s/.nvmrc' with version <lts/*>
Now using node v14.15.0 (npm v7.9.0)
```

It appears that `nvm use` will use whatever _you_ specified locally as `lts/*`. I'll update `.nvmrc` to point at specific version (in this case 14+) instead a generic `lts`.

**Comment by salcode** [comment]
Wow, great find. That is good to know. Thanks for the detective work.
